---
  - name: Loops experiments
    hosts: remote
    become: yes
    vars:
      packages: [git,vim,ruby]
    tasks:
      - name: Install packages
        apt:
          name: "{{ item }}"
          state: latest
        with_items: "{{ packages }}"
        
      - name: Recieve package facts
        package_facts:
          manager: auto

      - name: Print the package facts
        debug:
          msg: "Version of {{item}} is {{ ansible_facts.packages[item][0].version }}"
        with_items: "{{ packages}}"

