---
  - name: "Playbook"
    hosts: locals
    tasks:
      - name: "Test reachability"
        ansible.builtin.ping:
      - name: "Create file's directory"
        file:
          path: "/tmp/ansible"
          state: directory
      - name: "Create first file"
        copy:
          dest: "/tmp/ansible/my_test_01.txt"
          content: "This is the first file content"
      - name: "Create second file"
        copy:
          dest: "/tmp/ansible/my_test_02.txt"
          content: "This is the second file content"
      - name: "Read file content"
        debug:
        with_file:
          - "/tmp/ansible/my_test_01.txt"
          - "/tmp/ansible/my_test_02.txt"
