---
  - name: "Remote config"
    hosts: remote
    tasks:
      - name: "Test reachability"
        ping:
      - name: "Install nginx"
        become: yes
        apt:
          name: nginx
          state: present
