---
  - name: "My playbook"
    hosts: locals
    tasks:
      - name: "Test reachability"
        ansible.builtin.ping:
      - name: "Install stress"
        become: yes
        apt:
          name: stress
          state: present
         
