---
  - name: Make sure Web Server is running
    hosts: remote
    become: yes
    vars:
      webserver_message: "There is my message for template"

    tasks:
      - name: Check availability
        ping:

      - name: Start httpd
        tags: apache2
        service:
          name: apache2
          state: started

      - name: Create index.html using Jinja2
        template:
          src: template.j2
          dest: /var/www/html/index.html
